### ISSUE TITLE
Allow server-side calls from frontend to public-api (rather than using client-side calls)

### ISSUE THREAD

**Issue by eddie-rowe** [hashicorp-demoapp/frontend#35]
Client side calls currently break Hashicups for service-mesh implementations with Consul. 

As shown in the branch below, Hashicups will encounter errors when frontend attempts to communicate with public-api. 
https://github.com/hashicorp-demoapp/hashicups-setups/tree/consul-er-hc-k8s-update/local-k8s-consul-deployment

In past versions, NGINX proxied frontend requests to public-api. 
In the latest versions, the Next.js app directs the browser to communicate with public-api directly. 

When the Consul service mesh pattern (with transparent proxy enabled) is utilized, failures occur (screenshot attached).

We have workarounds for now, but are considering these factors for the future:
1. If we teach the workarounds, we would be directing folks in the respective tutorials to have three port-forwarding sessions open at once (consul, frontend, and public-api)
2. Having practitioners do this is kind of workaroundy/non-prod - it strays a bit from service mesh app to service mesh app communication and having a single point of ingress into a microservices app
3. I'm not sure yet, but I think it may have some strange intentions implication

I've also attached a screenshot of what I imagine the currently architecture problem is to help visualize what I'm describing.

<img width="1037" alt="k8s_consul_hashicups_app_architecture" src="https://user-images.githubusercontent.com/74205376/155228280-b5ae33b0-988e-403b-8915-c89530d055c5.png">
<img width="1783" alt="k8s_consul_hashicups_resolution_failure" src="https://user-images.githubusercontent.com/74205376/155228285-45938de0-727a-4ae4-8670-9be605eee409.png">

**Comment by jjti** [comment]
I ran into this when trying to bump the frontend for https://github.com/hashicorp/terraform-aws-hcp-consul

I agree with sentiment expressed by:

> Having practitioners do this is kind of workaroundy/non-prod - it strays a bit from service mesh app to service mesh app communication and having a single point of ingress into a microservices app

**Comment by jjti** [comment]
I got v1.0.2 to work in EKS/k8 by making a separate nginx service. PR here: https://github.com/hashicorp/terraform-aws-hcp-consul/pull/39. Based on @im2nguyen's work: 
- https://github.com/hashicorp-demoapp/hashicups-setups/tree/89b968844a0250995cbea71838425326a7486d64/docker-compose-deployment-reverse-proxy-nginx
- https://github.com/hashicorp-demoapp/frontend/commit/4f8b6444e1043339666870a638749f0586c1453a

So it's still a single entrypoint from web -> backend. And that single entrypoint is still nginx. But nginx is it's own service:
![Screen Shot 2022-03-21 at 9 32 07 PM](https://user-images.githubusercontent.com/13923102/159389589-da0b4a31-98c4-4ea4-9b60-e442889b46f1.png)

**Comment by im2nguyen** [comment]
Hey @jjtimmons and @eddie-rowe, [`hashicorpdemoapp/frontend-nginx:v1.0.9`](https://hub.docker.com/r/hashicorpdemoapp/frontend-nginx) supports this now!

this is the command to use it ([`nginx.conf`](https://github.com/hashicorp-demoapp/frontend/blob/main/nginx.conf) file) at the root directory 😄 

```
docker run -it -p 80:80 -v $PWD/nginx.conf:/etc/nginx/conf.d/default.conf --env NEXT_PUBLIC_FOOTER_FLAG=test123 hashicorpdemoapp/frontend-nginx:v1.0.9
```
