### ISSUE TITLE
CORS causing issues

### ISSUE THREAD

**Issue by karl-cardenas-coding** [hashicorp-demoapp/frontend#36]
Allows `cors` to support `*`. Otherwise scenarios using remote lab environments, such as Instruqt will fail due to CORS errors.

![image](https://user-images.githubusercontent.com/29551334/155240610-12c53c02-ddd1-40cf-8772-5dcac0bcee41.png)

**Comment by karl-cardenas-coding** [comment]
@im2nguyen  and @dizzyup 

I think we can address this by modifying the Apollo client to have the default value of `"*"` in the header value `Access-Control-Allow-Origin`.

```js
const authLink = setContext((_, { headers }) => {
  const token = JSON.parse(localStorage.getItem('token'))
  return {
    headers: {
      ...headers,
      'Access-Control-Allow-Origin': "*",
      Authorization: token ? `${token}` : "",
    }
  }
})
```

**Comment by im2nguyen** [comment]
That's interesting... usually CORS would be done on the server side. The public api should enable CORS for am hosts 🤔 

```
// Enable CORS for all hosts
	r.Use(cors.New(cors.Options{
		AllowedOrigins: []string{"*"},
		AllowedMethods: []string{"POST", "GET", "OPTIONS", "PUT", "DELETE"},
		AllowedHeaders: []string{"Accept", "content-type", "Content-Length", "Accept-Encoding", "X-CSRF-Token", "Authorization"},
	}).Handler)

```

**Comment by karl-cardenas-coding** [comment]
@im2nguyen I think the problem is that we have an authorization header along with * for CORS. I think Chrome is ignoring that * value. 

So we might have to update the API to allow domain `localhost`, and `*.instruqt.io`

**Comment by im2nguyen** [comment]
This was an Instruqt issue, gonna close!
