### ISSUE TITLE
Add a label that indicates that images of coffee cups can be slid in order to select other coffees

### ISSUE THREAD

**Issue by rberlind** [hashicorp-demoapp/frontend#9]
I've used the HashiCups app multiple times over the past few months while evaluating the Hackathon demos, but I only just learned this week that the images of the coffee cups can be slid left and right in order to select other coffees. I imagine a lot of people don't realize how to select coffees in the app.

I think it would very useful if we added a label to the top of the frontend screen that would say something like "Slide to Select your Coffee"

**Comment by rberlind** [comment]
An alternative idea from Chad Armitstead would be to put < and > arrows instead of a label and have users click on those instead of swiping.  Or support those and swiping.  Note that the < and > controls is what Instruqt uses for notes in all Instruqt tracks, so using those would be intuitive for all SEs who use Instruqt.

**Comment by karl-cardenas-coding** [comment]
@rberlind this will be addressed in the next version of Hashicups. We are working on releasing the new version now. We just have some integration work to wrap up.

**Comment by rberlind** [comment]
Thanks, @karl-cardenas-coding

**Comment by karl-cardenas-coding** [comment]
@rberlind are you comfortable with us closing this issue now that the new version of HashiCups is available?
